{% set maturin_version = ">=0.14,<0.15" %}
{% set maturin_version = ">=0.14,<0.15" %}
{% set version = "1.0.1" %}
{% set maturin_version = ">=0.14,<0.15" %}

package:
  name: fast-query-parsers
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fast-query-parsers/fast_query_parsers-{{ version }}.tar.gz
  sha256: 242615e036aa41b32362ddc50b4ac6b067571fd346f437702f1c3109b94c091f

build:
  skip: true  # [py<38]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - crossenv                               # [build_platform != target_platform]
    - maturin {{ maturin_version }}          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin {{ maturin_version }}
    - pip
    - python
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - fast_query_parsers
  commands:
    - pip check
    - pytest -vv --cov=fast_query_parsers --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=83
    - mypy -p fast_query_parsers
  requires:
    - mypy
    - pip
    - pytest-cov

about:
  home: https://github.com/starlite-api/fast-query-parsers
  summary: Ultra-fast query string and url-encoded form-data parsers
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
